version: "3.8"
services:
  backend:
    build: ./backend
    container_name: video-corte-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build: ./video-cutter/video-cutter
    container_name: video-corte-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
